context:
  name: roboplan
  version: "0.6.1"
  # Testing open-planning/roboplan#301 (allow-generating-conda-packages-from-pixi).
  git_rev: "8bd7b2ec35956b13e502c693abef4dc86050ade9"
  pinocchio_min: "4.0.0"
  pinocchio_max: "5.0.0"

recipe:
  name: roboplan
  version: ${{ version }}

source:
  url: https://github.com/open-planning/roboplan/archive/${{ git_rev }}.tar.gz
  sha256: d32bd18db792c11f1c842599630485f4a658aa93002ef18e3a5f167a92b58544

build:
  number: 0

outputs:
  - package:
      name: roboplan-common
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_common
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-common", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
      host:
        - python
      run:
        - python
    tests:
      - package_contents:
          site_packages:
            - roboplan_common
          files:
            - if: win
              then: Library/lib/cmake/roboplan_common/roboplan_commonConfig.cmake
              else: lib/cmake/roboplan_common/roboplan_commonConfig.cmake
      - python:
          pip_check: false
          imports:
            - roboplan_common

  - package:
      name: libroboplan-example-models
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan_example_models
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-example-models", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_example_models

  - package:
      name: roboplan-example-models-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_example_models
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-example-models-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
      run:
        - python
        - roboplan-common ==${{ version }}
        - numpy
        - pinocchio-python >=${{ pinocchio_min }},<${{ pinocchio_max }}
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_example_models
      - python:
          pip_check: false
          imports:
            - roboplan.example_models

  - package:
      name: libroboplan-core
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-core", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - libcoal
        - libpinocchio >=${{ pinocchio_min }},<${{ pinocchio_max }}
        - tinyxml2
        - yaml-cpp
        - libroboplan-example-models ==${{ version }}
        - eigen-abi-devel
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan

  - package:
      name: roboplan-core-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-core-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
        - libcoal
        - libpinocchio >=${{ pinocchio_min }},<${{ pinocchio_max }}
        - tinyxml2
        - yaml-cpp
        - roboplan-example-models-python ==${{ version }}
        - eigen-abi-devel
      run:
        - python
        - roboplan-common ==${{ version }}
        - numpy
        - pinocchio-python >=${{ pinocchio_min }},<${{ pinocchio_max }}
        - roboplan-example-models-python ==${{ version }}
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan
      - python:
          pip_check: false
          imports:
            - roboplan.core

  - package:
      name: libroboplan-oink
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan_oink
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-oink", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - libroboplan-core ==${{ version }}
        - libroboplan-example-models ==${{ version }}
        - proxsuite
        - eigen-abi-devel
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_oink

  - package:
      name: roboplan-oink-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_oink
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-oink-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - proxsuite
        - eigen-abi-devel
      run:
        - python
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_oink
      - python:
          pip_check: false
          imports:
            - roboplan.optimal_ik

  - package:
      name: libroboplan-rrt
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan_rrt
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-rrt", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - libroboplan-core ==${{ version }}
        - libroboplan-example-models ==${{ version }}
        - eigen-abi-devel
    tests:
      - package_contents:
          lib:
            - roboplan_rrt

  - package:
      name: roboplan-rrt-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_rrt
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-rrt-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - eigen-abi-devel
      run:
        - python
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
    tests:
      - package_contents:
          lib:
            - roboplan_rrt
      - python:
          pip_check: false
          imports:
            - roboplan.rrt

  - package:
      name: libroboplan-simple-ik
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan_simple_ik
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-simple-ik", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - libroboplan-core ==${{ version }}
        - libroboplan-example-models ==${{ version }}
        - eigen-abi-devel
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_simple_ik

  - package:
      name: roboplan-simple-ik-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_simple_ik
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-simple-ik-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - eigen-abi-devel
      run:
        - python
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_simple_ik
      - python:
          pip_check: false
          imports:
            - roboplan.simple_ik

  - package:
      name: libroboplan-toppra
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan_toppra
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-toppra", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - libroboplan-core ==${{ version }}
        - libroboplan-example-models ==${{ version }}
        - libtoppra
        - eigen-abi-devel
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_toppra

  - package:
      name: roboplan-toppra-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_toppra
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-toppra-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - libtoppra
        - eigen-abi-devel
      run:
        - python
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_toppra
      - python:
          pip_check: false
          imports:
            - roboplan.toppra

  - package:
      name: libroboplan-cartesian-planning
      version: ${{ version }}
    build:
      script:
        file: build_cpp
        env:
          ROBOPLAN_PACKAGE: roboplan_cartesian_planning
    requirements:
      run_exports:
        - ${{ pin_subpackage("libroboplan-cartesian-planning", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - libroboplan-core ==${{ version }}
        - libroboplan-example-models ==${{ version }}
        - libroboplan-oink ==${{ version }}
        - libroboplan-toppra ==${{ version }}
        - eigen-abi-devel
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_cartesian_planning

  - package:
      name: roboplan-cartesian-planning-python
      version: ${{ version }}
    build:
      script:
        file: build_python
        env:
          ROBOPLAN_PACKAGE: roboplan_cartesian_planning
    requirements:
      run_exports:
        - ${{ pin_subpackage("roboplan-cartesian-planning-python", upper_bound="x.x.x") }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
      host:
        - if: win
          then: dlfcn-win32
        - gtest
        - python
        - nanobind
        - if: match(python, "<3.11")
          then: typing_extensions
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - roboplan-oink-python ==${{ version }}
        - roboplan-toppra-python ==${{ version }}
        - libtoppra
        - eigen-abi-devel
      run:
        - python
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - roboplan-oink-python ==${{ version }}
        - roboplan-toppra-python ==${{ version }}
      ignore_run_exports:
        by_name:
          - gtest
        from_package:
          - gtest
    tests:
      - package_contents:
          lib:
            - roboplan_cartesian_planning
      - python:
          pip_check: false
          imports:
            - roboplan.cartesian_planning

  - package:
      name: libroboplan
      version: ${{ version }}
    requirements:
      run:
        - libroboplan-core ==${{ version }}
        - libroboplan-example-models ==${{ version }}
        - libroboplan-oink ==${{ version }}
        - libroboplan-rrt ==${{ version }}
        - libroboplan-simple-ik ==${{ version }}
        - libroboplan-toppra ==${{ version }}
        - libroboplan-cartesian-planning ==${{ version }}
    tests:
      - script:
          file: test_libs
        files:
          recipe:
            - test_libs.sh
            - test_libs.bat

  - package:
      name: roboplan-python
      version: ${{ version }}
    requirements:
      run:
        - python
        - roboplan-common ==${{ version }}
        - roboplan-core-python ==${{ version }}
        - roboplan-example-models-python ==${{ version }}
        - roboplan-oink-python ==${{ version }}
        - roboplan-rrt-python ==${{ version }}
        - roboplan-simple-ik-python ==${{ version }}
        - roboplan-toppra-python ==${{ version }}
        - roboplan-cartesian-planning-python ==${{ version }}
    tests:
      - script:
          file: test_libs
        files:
          recipe:
            - test_libs.sh
            - test_libs.bat
      - python:
          pip_check: false
          imports:
            - roboplan_common
            - roboplan.core
            - roboplan.example_models
            - roboplan.optimal_ik
            - roboplan.rrt
            - roboplan.simple_ik
            - roboplan.toppra
            - roboplan.cartesian_planning

about:
  homepage: https://github.com/open-planning/roboplan
  license: MIT
  license_file: LICENSE
  summary: Modern robot motion planning library based on Pinocchio.
  repository: https://github.com/open-planning/roboplan
  documentation: https://roboplan.readthedocs.io/en/latest/

extra:
  feedstock-name: roboplan
  recipe-maintainers:
    - sea-bass
    - eholum
